<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>verify</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\HanConverter.cs" Link="HanConverter.cs" />
    <Compile Include="..\..\HanConverterData.cs" Link="HanConverterData.cs" />
    <Compile Include="..\..\UnifiedNames.cs" Link="UnifiedNames.cs" />
    <Compile Remove="VerifyDll.cs" />
  </ItemGroup>
</Project>
