// Generate UiDict.cs: UI dictionary (JP -> Simplified CN) with values
// converted from Traditional via the same OpenCC tables.
import fs from 'node:fs';

const DIR = 'E:/dsh/TSKHook/tools/opencc-data';
const XDIR = 'E:/dsh/TSKHook/tools/xlsx-extract';

function loadDict(file, sep = '\t') {
  const lines = fs.readFileSync(`${DIR}/${file}`, 'utf8').split('\n');
  const map = new Map();
  for (const line of lines) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const parts = t.split(sep).map((s) => s.trim()).filter(Boolean);
    if (parts.length < 2) continue;
    map.set(parts[0], parts.slice(1));
  }
  return map;
}
const chars = loadDict('TSCharacters.txt');
const tsPhrases = loadDict('TSPhrases.txt');
const twPhrases = loadDict('TWPhrases.txt');
const manualTW = JSON.parse(fs.readFileSync(`${DIR}/manual_tw_cn.json`, 'utf8'));
const phraseMap = new Map();
for (const [tw, cn] of Object.entries(manualTW)) phraseMap.set(tw, cn);
for (const [cn, twList] of twPhrases) for (const tw of twList) if (!phraseMap.has(tw)) phraseMap.set(tw, cn);
for (const [tw, cnList] of tsPhrases) if (!phraseMap.has(tw)) phraseMap.set(tw, Array.isArray(cnList) ? cnList[0] : cnList);
function toSimplified(text) {
  if (!text) return text;
  let out = '';
  let i = 0;
  while (i < text.length) {
    let matched = false;
    const maxLen = Math.min(6, text.length - i);
    for (let len = maxLen; len >= 2; len--) {
      const key = text.substr(i, len);
      if (phraseMap.has(key)) {
        const val = phraseMap.get(key);
        if (val === key) continue;
        out += val; i += len; matched = true; break;
      }
    }
    if (matched) continue;
    const ch = text[i];
    out += chars.has(ch) ? String(chars.get(ch)).split(' ')[0] : ch;
    i++;
  }
  return out;
}

const raw = JSON.parse(fs.readFileSync(`${XDIR}/ui_dict_raw.json`, 'utf8'));
const converted = {};
for (const [k, v] of Object.entries(raw)) converted[k] = toSimplified(v);

// dedupe: keep first occurrence, skip identity
const final = {};
for (const [k, v] of Object.entries(converted)) {
  if (!v || v === k) continue; // skip empty/identity
  if (!final[k]) final[k] = v;
}

function cs(s) {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

let out = `// Auto-generated by tools/gen-ui-dict.mjs
// UI dictionary: Japanese interface text -> Simplified Chinese.
// Sources: platform slang/terminology + manually curated common UI terms.
using System.Collections.Generic;

namespace TSKHook;

public static class UiDict
{
    public static readonly Dictionary<string, string> Entries = new()
    {
`;
for (const [k, v] of Object.entries(final)) {
  out += `        { "${cs(k)}", "${cs(v)}" },\n`;
}
out += `    };
}
`;

fs.writeFileSync('E:/dsh/TSKHook/UiDict.cs', out, 'utf8');
console.log('UiDict.cs written, entries:', Object.keys(final).length, 'size:', out.length);
// show sample conversions
let n = 0;
for (const [k, v] of Object.entries(final)) {
  console.log(`  ${k} => ${v}`);
  if (++n >= 20) break;
}
