// STRICT verification: every Harmony target in my patched code must exist
// in the FRESH interop assemblies (generated by official BepInEx on clean game).
// This time we verify properly using the IL2CPP member-pointer naming convention:
// IL2CPP interop exposes members as NativeMethodInfoPtr_<Name>_<Access>_<Return>_<Type>
// We check for exact "<Type>...get_NameText" patterns in the type's member block.
import fs from 'node:fs';

const dll = (process.env.TSK_GAME || 'C:/Path/To/Twinkle_StarKnightsX') + '/BepInEx/interop/Assembly-CSharp.dll';
const buf = fs.readFileSync(dll);
const text = buf.toString('latin1');
console.log('scanning', dll, buf.length, 'bytes\n');

// Helper: find if a method exists as member of a type using the IL2CPP naming:
// NativeMethodInfoPtr_<method>_<access>_<return>_<Type>_<n>
function methodExists(typeName, methodName) {
  // pattern: methodName followed by _Public/_Private/_Protected/_Internal etc and then ..._TypeName
  const re = new RegExp(`${methodName}_[A-Za-z]+_[A-Za-z0-9]+_${typeName}`, 'g');
  const matches = text.match(re);
  return matches ? matches.length : 0;
}

// Check ALL Harmony targets used in my Patch.cs
const targets = [
  ['GameConfig', 'set_FixedFrameRate'],
  ['AdvDataManager', 'DownloadChaperKeyFileUsed'],
  ['AdventureTitleBandView', 'Initialize'],
  ['UguiNovelText', 'OnEnable'],
  ['AdvPage', 'get_NameText'],
  ['AdvBacklog', 'get_MainCharacterNameText'],
  ['LanguageManagerBase', 'ParseCellLocalizedTextBySwapDefaultLanguage'],
  ['Screen', 'SetResolution'],
  ['MaximizeCharaView', 'SetCharaRoot_Scale'],
  ['MaximizeCharaView', 'initialize'],
];

console.log('=== Harmony targets in fresh interop ===');
let allOk = true;
for (const [type, method] of targets) {
  const n = methodExists(type, method);
  const ok = n > 0;
  if (!ok) allOk = false;
  console.log(`${ok ? 'OK  ' : 'MISS'} ${type}.${method} (${n})`);
}

// Also verify the FONT asset loading types
console.log('\n=== font / TMP types ===');
for (const t of ['TMP_FontAsset', 'AssetBundle']) {
  const found = text.includes(t) || fs.readFileSync((process.env.TSK_GAME || 'C:/Path/To/Twinkle_StarKnightsX') + '/BepInEx/interop/Unity.TextMeshPro.dll').toString('latin1').includes(t);
  console.log(`${found ? 'OK  ' : 'MISS'} ${t}`);
}
console.log(allOk ? '\nALL CORE HOOK TARGETS PRESENT ✓' : '\nSOME TARGETS MISSING!');
